/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardDisplay: typeof import('./src/components/card/Card-Display.vue')['default']
    CardModal: typeof import('./src/components/card/Card-Modal.vue')['default']
    CardPost: typeof import('./src/components/card/Card-Post.vue')['default']
    FabContainer: typeof import('./src/components/Fab-Container.vue')['default']
    MapContainer: typeof import('./src/components/Map-Container.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'Var-': typeof import('@varlet/ui')['_-Component']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarDrag: typeof import('@varlet/ui')['_DragComponent']
    VarFab: typeof import('@varlet/ui')['_FabComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarImage: typeof import('@varlet/ui')['_ImageComponent']
    VarImagePreview: typeof import('@varlet/ui')['_ImagePreviewComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarOverlay: typeof import('@varlet/ui')['_OverlayComponent']
    VarPaper: typeof import('@varlet/ui')['_PaperComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
  }
}
