/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardDisplay: typeof import('./src/components/card/Card-Display.vue')['default']
    CardModal: typeof import('./src/components/card/Card-Modal.vue')['default']
    CardPost: typeof import('./src/components/card/Card-Post.vue')['default']
    FabContainer: typeof import('./src/components/Fab-Container.vue')['default']
    FixedMusicPlayer: typeof import('./src/components/music-player/Fixed-Music-Player.vue')['default']
    MapContainer: typeof import('./src/components/Map-Container.vue')['default']
    MusicPlayer: typeof import('./src/components/music-player/Music-Player.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestCard1: typeof import('./src/components/card/diy/Test-Card1.vue')['default']
    UnfixedMusicPlayer: typeof import('./src/components/music-player/Unfixed-Music-Player.vue')['default']
    VarAvatar: typeof import('@varlet/ui')['_AvatarComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarFab: typeof import('@varlet/ui')['_FabComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarImage: typeof import('@varlet/ui')['_ImageComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarPaper: typeof import('@varlet/ui')['_PaperComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarSwipe: typeof import('@varlet/ui')['_SwipeComponent']
    VarSwipeItem: typeof import('@varlet/ui')['_SwipeItemComponent']
    VarTooltip: typeof import('@varlet/ui')['_TooltipComponent']
  }
}
